// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmE5TlJqZh4tQEkHtYPYiUDU6YaIXVq-I',
    appId: '1:811323156331:web:dee15c3935494abc868e2e',
    messagingSenderId: '811323156331',
    projectId: 'test-flutter-55267',
    authDomain: 'test-flutter-55267.firebaseapp.com',
    storageBucket: 'test-flutter-55267.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd5S5NdLbGkJtkUDxuHuUgAIiZVTQAmsM',
    appId: '1:811323156331:android:91b44caa02cb13c0868e2e',
    messagingSenderId: '811323156331',
    projectId: 'test-flutter-55267',
    storageBucket: 'test-flutter-55267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwv_hSWip06JS00JkdTvFlT_U0XzDiE9Y',
    appId: '1:811323156331:ios:97d653b3f0a75054868e2e',
    messagingSenderId: '811323156331',
    projectId: 'test-flutter-55267',
    storageBucket: 'test-flutter-55267.appspot.com',
    androidClientId: '811323156331-bt2qqca86ettlnikjtunlc3cntdr643n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwv_hSWip06JS00JkdTvFlT_U0XzDiE9Y',
    appId: '1:811323156331:ios:35e337342d88d5f3868e2e',
    messagingSenderId: '811323156331',
    projectId: 'test-flutter-55267',
    storageBucket: 'test-flutter-55267.appspot.com',
    androidClientId: '811323156331-bt2qqca86ettlnikjtunlc3cntdr643n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksApp.RunnerTests',
  );
}
